<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Availability extends Model
{
    protected $table = 'availability';

    protected $fillable = [
        'product_id',
        'date',
        'available_unit',
        'available_seat',
        'is_overridden',
        'override_reason',
        'overridden_by',
        'overridden_at',
    ];

    protected $casts = [
        'date' => 'datetime',
        'is_overridden' => 'boolean',
        'overridden_at' => 'datetime',
    ];

    // ===== relationships =======
    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }

    public function overriddenByUser()
    {
        return $this->belongsTo(User::class, 'overridden_by');
    }


    // ===== DATE MUTATOR  ====
    public function setDateAttribute($value)
    {
        // Convert any date format to Carbon and set to start of day
        $this->attributes['date'] = Carbon::parse($value)->startOfDay();
    }

    public function getDateStringAttribute()
    {
        return $this->date->format('Y-m-d');
    }



    // ===== scope =======
    public function scopeForDate($query, $date)
    {
        return $query->whereDate('date', Carbon::parse($date)->format('Y-m-d'));
    }
    public function scopeDateBetween($query, $startDate, $endDate)
    {
        return $query->whereBetween('date', [
            Carbon::parse($startDate)->startOfDay(),
            Carbon::parse($endDate)->endOfDay(),
        ]);
    }
    public function scopeDateRange($query, $startDate, $endDate)
    {
        return $query->whereBetween('date', [$startDate, $endDate]);
    }

    public function scopeOnDate($query, $date)
    {
        return $query->where('date', Carbon::parse($date)->toDateString());
    }
    public function scopeAvailable($query)
    {
        return $query
            ->whereNotNull('available_units')
            ->where('available_units', '>', 0);
    }

    public function scopeOverriden($query)
    {
        return $query->where('is_overridden', true);
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('is_overridden', false);
    }

    // ========== methods ==========
    public function markAsOverridden($userId, $reason = null)
    {
        $this->update([
            'is_overridden' => true,
            'override_reason' => $reason,
            'overridden_by' => $userId,
            'overridden_at' => now(),
        ]);
    }

    public function resetOverride()
    {

        // Option 1: Use a default constant
        $defaultUnit = $this->product->type === 'touring' ? 0 : 20;
        $defaultSeat = $this->product->type === 'touring' ? 20 : 0;

        $this->update([
            'available_unit' => $defaultUnit,
            'available_seat' => $defaultSeat,
            'is_overridden' => false,
            'override_reason' => null,
            'overridden_by' => null,
            'overridden_at' => null,
        ]);
    }

    public function isLowStock()
    {
        // ✅ FIX: Check against first availability record as baseline
        $firstAvailability = Availability::where('product_id', $this->product_id)
            ->where('is_overridden', false)
            ->orderBy('date', 'asc')
            ->first();

        if (!$firstAvailability) {
            return false;
        }

        if ($this->product->type === 'touring') {
            $threshold = $firstAvailability->available_seat * 0.5;
            return $this->available_seat < $threshold; // ✅ FIX typo: availability_seat → available_seat
        } else {
            $threshold = $firstAvailability->available_unit * 0.5;
            return $this->available_unit < $threshold;
        }
    }

    public function isFullyBooked()
    {
        if ($this->product->type === 'touring') {
            return $this->available_seat <= 0; // ✅ FIX typo
        } else {
            return $this->available_unit <= 0;
        }
    }

    public function getStockStatusColor() // ✅ FIX typo: color bukan colour
    {
        if ($this->isFullyBooked()) {
            return 'red';
        } elseif ($this->isLowStock()) {
            return 'yellow';
        } else {
            return 'green';
        }
    }

    public function getStockPercentage()
    {
        // ✅ Use first availability as baseline
        $firstAvailability = Availability::where('product_id', $this->product_id)
            ->where('is_overridden', false)
            ->orderBy('date', 'asc')
            ->first();

        if (!$firstAvailability) {
            return 100;
        }

        if ($this->product->type === 'touring') {
            $total = $firstAvailability->available_seat;
            return $total > 0 ? ($this->available_seat / $total) * 100 : 0;
        } else {
            $total = $firstAvailability->available_unit;
            return $total > 0 ? ($this->available_unit / $total) * 100 : 0;
        }
    }


    public function hasAvailableUnits($needed = 1)
    {
        return $this->available_unit !== null && $this->available_unit >= $needed;
    }

    public function hasAvailableSeats($needed = 1)
    {
        return $this->available_seat !== null && $this->available_seat >= $needed;
    }

    public function decreaseSeats($qty)
    {
        if ($this->available_seat !== null) {
            $this->available_seat = max(0, $this->available_seat - $qty);
            $this->save();
        }
    }

    public function increaseSeats($qty)
    {
        if ($this->available_seat !== null) {
            $this->available_seat += $qty;
            $this->save();
        }
    }
}
